<?php
/**
 * Multiple Layered Navigation
 * 
 * @author Slava Yurthev
 */
?>
<ol class="items">
	<?php foreach ($filterItems as $filterItem): ?>
		<li class="item">
			<?php if ($filterItem->getCount() > 0 && !$filterItem->isActive()): ?>
				<a href="<?php if($filterItem->isActive()): ?><?php echo $block->escapeUrl($filterItem->getRemoveUrl()); ?><?php else: ?><?php echo $block->escapeUrl($filterItem->getUrl()); ?><?php endif; ?>">
					<?php echo $filterItem->getLabel(); ?>
					<?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
						<span class="count"><?php echo $filterItem->getCount() ?><span class="filter-count-label"><?php if ($filterItem->getCount() == 1):?><?php echo __('item'); ?><?php else: ?><?php echo __('items'); ?><?php endif; ?></span></span>
					<?php endif; ?>
				</a>
			<?php else:?>
				<?php echo $filterItem->getLabel(); ?>
				<?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
					<span class="count"><?php echo $filterItem->getCount() ?><span class="filter-count-label"><?php if ($filterItem->getCount() == 1):?><?php echo __('item'); ?><?php else: ?><?php echo __('items'); ?><?php endif; ?></span></span>
				<?php endif; ?>
			<?php endif; ?>
		</li>
	<?php endforeach ?>
</ol>